# Trained with Tesla V100-SXM2(32GB) x 8 GPUs. It takes about 1.5 days.
batch_type: numel
#batch_bins: 140000000
batch_bins: 280000
accum_grad: 6
max_epoch: 35
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
chunk_length: 500                                                                                                                                                                                                                         
chunk_shift_ratio: 0.5 

init_param: 
    - /usr0/home/yitingye/miniconda3/envs/odml/lib/python3.7/site-packages/espnet_model_zoo/653d10049fdc264f694f57b49849343e/exp/asr_train_asr_transformer_e18_raw_bpe_sp/54epoch.pth

encoder: transformer
encoder_conf:
    attention_dropout_rate: 0.1                                                                                                                                                                                                             
    attention_heads: 8                                                                                                                                                                                                                      
    dropout_rate: 0.1                                                                                                                                                                                                                       
    input_layer: conv2d6                                                                                                                                                                                                                    
    linear_units: 2048                                                                                                                                                                                                                      
    normalize_before: true                                                                                                                                                                                                                  
    num_blocks: 18                                                                                                                                                                                                                          
    output_size: 512                                                                                                                                                                                                                        
    positional_dropout_rate: 0.1  
    stochastic_depth_rate: 0.3
    intermediate_layers: 
    - 6
    - 12

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend: default
frontend_conf:
    fs: 16k

specaug_conf:                                                                                                                                                                                                                             
    apply_freq_mask: true                                                                                                                                                                                                                   
    apply_time_mask: true                                                                                                                                                                                                                   
    apply_time_warp: true                                                                                                                                                                                                                   
    freq_mask_width_range:                                                                                                                                                                                                                  
    - 0                                                                                                                                                                                                                                     
    - 30                                                                                                                                                                                                                                    
    num_freq_mask: 2                                                                                                                                                                                                                        
    num_time_mask: 2                                                                                                                                                                                                                        
    time_mask_width_range:                                                                                                                                                                                                                  
    - 0                                                                                                                                                                                                                                     
    - 40                                                                                                                                                                                                                                    
    time_warp_mode: bicubic                                                                                                                                                                                                                 
    time_warp_window: 5  